AllCops:
  TargetRubyVersion: 2.7.3
  NewCops: enable

Layout/LineLength:
  Max: 120

Metrics/CyclomaticComplexity:
  Max: 15

Style/RescueModifier:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false
